# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/brian/545/Geoff/Geoff.cache/wt [current_project]
set_property parent.project_path /home/brian/545/Geoff/Geoff.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/dma_loopback.bd
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_axi_dma_0_0/dma_loopback_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_axi_dma_0_0/dma_loopback_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_axi_dma_0_0/dma_loopback_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_processing_system7_0_0/dma_loopback_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_rst_processing_system7_0_50M_0/dma_loopback_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_rst_processing_system7_0_50M_0/dma_loopback_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_rst_processing_system7_0_50M_0/dma_loopback_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_xbar_0/dma_loopback_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_xbar_1/dma_loopback_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_pc_0/dma_loopback_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_pc_1/dma_loopback_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_pc_2/dma_loopback_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_us_0/dma_loopback_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_us_0/dma_loopback_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_us_1/dma_loopback_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_us_1/dma_loopback_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_us_2/dma_loopback_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/ip/dma_loopback_auto_us_2/dma_loopback_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/dma_loopback_ooc.xdc]
set_property is_locked true [get_files /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/dma_loopback.bd]

read_verilog -library xil_defaultlib -sv {
  /home/brian/545/Geoff/Geoff.srcs/sources_1/bd/dma_loopback/hdl/dma_loopback_wrapper.v
  /home/brian/545/DMA_Loopback/DMA_Loopback.srcs/vga.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Property_of_Geoff/VGA_INTERFACE.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Geoff.srcs/feature_response_calc.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Geoff.srcs/CHIP_INTERFACE.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Geoff.srcs/classifier_module.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Geoff.srcs/job_packet_builder.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Geoff.srcs/job_packet_queue.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Geoff.srcs/next_roi.sv
  /home/brian/545/Geoff/Geoff.srcs/sources_1/imports/Geoff.srcs/feature_processor.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brian/545/zedboard_master_XDC_RevC_D_v3.xdc
set_property used_in_implementation false [get_files /home/brian/545/zedboard_master_XDC_RevC_D_v3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dma_loopback_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef dma_loopback_wrapper.dcp

catch { report_utilization -file dma_loopback_wrapper_utilization_synth.rpt -pb dma_loopback_wrapper_utilization_synth.pb }
